import {test,expect,request as createRequest} from '@playwright/test';
import {Pool} from 'pg';import {hash} from 'bcryptjs';import {randomBytes} from 'node:crypto';
const database=process.env.DATABASE_URL;
test.describe('PostgreSQL authenticated workflows',()=>{
 test.skip(!database,'Dedicated PostgreSQL not available');
 const suffix=randomBytes(8).toString('hex');const password=randomBytes(24).toString('base64');const emails:Record<string,string>={};let pool:Pool;let productId:string;let assetId:string;const records:string[]=[];
 test.beforeAll(async()=>{pool=new Pool({connectionString:database});for(const role of ['editor','reviewer','viewer']){emails[role]=`${role}-${suffix}@example.invalid`;await pool.query('INSERT INTO studio_users(email,display_name,role,password_hash) VALUES($1,$2,$3,$4)',[emails[role],role,role,await hash(password,12)]);}});
 test.afterAll(async()=>{if(!pool)return;await pool.query('DELETE FROM studio_reviews WHERE record_id=ANY($1::uuid[])',[records]);await pool.query('DELETE FROM studio_audit_log WHERE actor_user_id IN (SELECT id FROM studio_users WHERE email=ANY($1))',[Object.values(emails)]);await pool.query('DELETE FROM studio_records WHERE created_by IN (SELECT id FROM studio_users WHERE email=ANY($1))',[Object.values(emails)]);await pool.query('DELETE FROM studio_users WHERE email=ANY($1)',[Object.values(emails)]);await pool.end();});
 async function login(role:string){const context=await createRequest.newContext({baseURL:process.env.APP_URL??'http://localhost:3000',extraHTTPHeaders:{Origin:process.env.APP_URL??'http://localhost:3000'}});const response=await context.post('/api/auth/login',{data:{email:emails[role],password}});expect(response.status()).toBe(200);expect(response.headers()['set-cookie']).toContain('HttpOnly');return context;}
 test('product uniqueness, real-photo linkage and independent QA',async()=>{const editor=await login('editor');const body={title:'Synthetic test product',data:{sku:'TEST-'+suffix,brand:'Test',description:'Synthetic test fixture',supplierCode:'',applications:'',applicationsVerified:false}};let result=await editor.post('/api/records/products',{data:body});expect(result.status()).toBe(201);productId=(await result.json()).id;records.push(productId);expect((await editor.post('/api/records/products',{data:body})).status()).toBe(409);
 result=await editor.post('/api/records/assets',{data:{title:'Synthetic photo reference',data:{productId,url:'https://example.invalid/test.jpg',source:'Test fixture',rightsConfirmed:true,realPhoto:true}}});expect(result.status()).toBe(201);assetId=(await result.json()).id;records.push(assetId);
 expect((await editor.post('/api/reviews',{data:{recordId:productId,decision:'approved',checklist:{},notes:'Test'}})).status()).toBe(403);
 const viewer=await login('viewer');expect((await viewer.get('/api/records/products')).status()).toBe(200);expect((await viewer.post('/api/records/products',{data:body})).status()).toBe(403);
 const reviewer=await login('reviewer');expect((await reviewer.post('/api/reviews',{data:{recordId:productId,decision:'approved',checklist:{},notes:'Incomplete'}})).status()).toBe(400);
 expect((await reviewer.post('/api/reviews',{data:{recordId:productId,decision:'approved',checklist:{fidelity:true,portuguese:true,brand:true,rights:true,dimensions:true},notes:'Synthetic fixture verified'}})).status()).toBe(200);
 expect((await reviewer.get('/api/records/products')).status()).toBe(200);await editor.post('/api/auth/logout');expect((await editor.get('/api/auth/me')).status()).toBe(401);await editor.dispose();await viewer.dispose();await reviewer.dispose();});
 test('UI login and module navigation',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/login');await page.getByLabel('E-mail').fill(emails.viewer);await page.getByLabel('Senha').fill(password);await page.getByRole('button',{name:'Entrar'}).click();await expect(page.getByRole('heading',{name:'Produtos e SKUs',exact:true})).toBeVisible();await page.getByRole('button',{name:'Biblioteca de imagens',exact:true}).click();await expect(page.getByRole('heading',{name:'Biblioteca de imagens',exact:true})).toBeVisible();await page.getByRole('button',{name:'Sair',exact:true}).click();await expect(page).toHaveURL(/login/);expect(errors).toEqual([]);});
});
